services:
  mysql:
    image: mysql:8.0
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_ME_mysql_root
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: CHANGE_ME_mysql_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: auth-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    entrypoint: sh
    command: -c "minio server /data --console-address ':9001' & sleep 5 && /usr/bin/minio-init.sh && tail -f /dev/null"
    container_name: minio
    # networks:
    #   trusted-client:
    restart: always
    environment:
      TZ: UTC
      MINIO_ROOT_USER: trusted-client
      MINIO_ROOT_PASSWORD: CHANGE_ME_minio_root
      MINIO_REGION: us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - minio_data:/data
      - ./minio-init.sh:/usr/bin/minio-init.sh
    ports:
      - "9002:9000" # 测试用
      - "9003:9001"

  auth-server:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: auth-server
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config/config.yaml
      - ./oidc-private-key.pem:/app/config/oidc-private-key.pem:ro
    ports:
      - "8080:80"

  oidc-demo:
    image: nginx:alpine
    container_name: auth-oidc-demo
    restart: always
    volumes:
      - ./oidc-demo:/usr/share/nginx/html:ro
    ports:
      - "3000:80"

volumes:
  mysql_data:
  redis_data:
  minio_data:
